In [1]:
from google.colab import files
up = files.upload()

Saving 100_Unique_QA_Dataset.csv to 100_Unique_QA_Dataset.csv

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("/content/100_Unique_QA_Dataset.csv")
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

* S1) Tokenize

In [101]:
import re
def tokenizeText(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return text.split()

In [89]:
tokenizeText("What is AI?")

['what', 'is', 'ai']

* S2) Vocab

In [102]:
def buildVocab(row):
  tokenizedQues = tokenizeText(row['question'])
  tokenizedAns = tokenizeText(row['answer'])
  mergedTokens = tokenizedQues + tokenizedAns
  for token in mergedTokens:
    if token not in vocab:
      vocab[token] = len(vocab)

In [103]:
vocab = {'<UNK>': 0}
df.apply(buildVocab, axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [93]:
len(vocab)

324

In [104]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper': 16,
 'lee': 17,
 'largest': 18,
 'planet': 19,
 'in': 20,
 'our': 21,
 'solar': 22,
 'system': 23,
 'jupiter': 24,
 'boiling': 25,
 'point': 26,
 'water': 27,
 'celsius': 28,
 '100': 29,
 'painted': 30,
 'mona': 31,
 'lisa': 32,
 'leonardo': 33,
 'da': 34,
 'vinci': 35,
 'square': 36,
 'root': 37,
 '64': 38,
 '8': 39,
 'chemical': 40,
 'symbol': 41,
 'for': 42,
 'gold': 43,
 'au': 44,
 'which': 45,
 'year': 46,
 'did': 47,
 'world': 48,
 'war': 49,
 'ii': 50,
 'end': 51,
 '1945': 52,
 'longest': 53,
 'river': 54,
 'nile': 55,
 'japan': 56,
 'tokyo': 57,
 'developed': 58,
 'theory': 59,
 'relativity': 60,
 'albert': 61,
 'einstein': 62,
 'freezing': 63,
 'fahrenheit': 64,
 '32': 65,
 'known': 66,
 'as': 67,
 'red': 68,
 'mars': 69,
 'author': 70,
 '1984': 71,
 'george': 72,
 'orwell': 73,
 'currency': 74,
 'united': 75,
 'kingdom': 76,
 'pound': 77,
 'india': 78,
 'delhi': 79,
 'discovered': 80,
 'gravity': 81,
 'newton': 82,
 'how': 83,
 'many': 84,
 'continents': 85,
 'are': 86,
 'there': 87,
 'on': 88,
 'earth': 89,
 '7': 90,
 'gas': 91,
 'do': 92,
 'plants': 93,
 'use': 94,
 'photosynthesis': 95,
 'co2': 96,
 'smallest': 97,
 'prime': 98,
 'number': 99,
 '2': 100,
 'invented': 101,
 'telephone': 102,
 'alexander': 103,
 'graham': 104,
 'bell': 105,
 'australia': 106,
 'canberra': 107,
 'ocean': 108,
 'pacific': 109,
 'speed': 110,
 'light': 111,
 'vacuum': 112,
 '299': 113,
 '792': 114,
 '458m': 115,
 's': 116,
 'language': 117,
 'spoken': 118,
 'brazil': 119,
 'portuguese': 120,
 'penicillin': 121,
 'fleming': 122,
 'canada': 123,
 'ottawa': 124,
 'mammal': 125,
 'whale': 126,
 'element': 127,
 'has': 128,
 'atomic': 129,
 '1': 130,
 'hydrogen': 131,
 'tallest': 132,
 'mountain': 133,
 'everest': 134,
 'city': 135,
 'big': 136,
 'apple': 137,
 'newyork': 138,
 'planets': 139,
 'starry': 140,
 'night': 141,
 'vangogh': 142,
 'formula': 143,
 'h2o': 144,
 'italy': 145,
 'rome': 146,
 'country': 147,
 'famous': 148,
 'sushi': 149,
 'was': 150,
 'first': 151,
 'person': 152,
 'step': 153,
 'moon': 154,
 'armstrong': 155,
 'main': 156,
 'ingredient': 157,
 'guacamole': 158,
 'avocado': 159,
 'sides': 160,
 'does': 161,
 'hexagon': 162,
 'have': 163,
 '6': 164,
 'china': 165,
 'yuan': 166,
 'pride': 167,
 'and': 168,
 'prejudice': 169,
 'jane': 170,
 'austen': 171,
 'iron': 172,
 'fe': 173,
 'hardest': 174,
 'natural': 175,
 'substance': 176,
 'diamond': 177,
 'continent': 178,
 'by': 179,
 'area': 180,
 'asia': 181,
 'president': 182,
 'states': 183,
 'washington': 184,
 'bird': 185,
 'its': 186,
 'ability': 187,
 'mimic': 188,
 'sounds': 189,
 'parrot': 190,
 'running': 191,
 'animated': 192,
 'tv': 193,
 'show': 194,
 'simpsons': 195,
 'vaticancity': 196,
 'most': 197,
 'moons': 198,
 'saturn': 199,
 'romeo': 200,
 'juliet': 201,
 'shakespeare': 202,
 'atmosphere': 203,
 'nitrogen': 204,
 'bones': 205,
 'adult': 206,
 'human': 207,
 'body': 208,
 '206': 209,
 'metal': 210,
 'liquid': 211,
 'at': 212,
 'room': 213,
 'temperature': 214,
 'mercury': 215,
 'russia': 216,
 'moscow': 217,
 'electricity': 218,
 'benjamin': 219,
 'franklin': 220,
 'second': 221,
 'land': 222,
 'color': 223,
 'ripe': 224,
 'banana': 225,
 'yellow': 226,
 'month': 227,
 '28': 228,
 'days': 229,
 'common': 230,
 'february': 231,
 'study': 232,
 'living': 233,
 'organisms': 234,
 'called': 235,
 'biology': 236,
 'home': 237,
 'great': 238,
 'wall': 239,
 'bees': 240,
 'collect': 241,
 'from': 242,
 'flowers': 243,
 'nectar': 244,
 'opposite': 245,
 'day': 246,
 'south': 247,
 'korea': 248,
 'seoul': 249,
 'bulb': 250,
 'edison': 251,
 'humans': 252,
 'breathe': 253,
 'survival': 254,
 'oxygen': 255,
 '144': 256,
 '12': 257,
 'pyramids': 258,
 'giza': 259,
 'egypt': 260,
 'sea': 261,
 'creature': 262,
 'eight': 263,
 'arms': 264,
 'octopus': 265,
 'holiday': 266,
 'celebrated': 267,
 'december': 268,
 '25': 269,
 'christmas': 270,
 'yen': 271,
 'legs': 272,
 'spider': 273,
 'sport': 274,
 'uses': 275,
 'net': 276,
 'ball': 277,
 'hoop': 278,
 'basketball': 279,
 'kangaroos': 280,
 'female': 281,
 'minister': 282,
 'uk': 283,
 'margaretthatcher': 284,
 'fastest': 285,
 'animal': 286,
 'cheetah': 287,
 'periodic': 288,
 'table': 289,
 'spain': 290,
 'madrid': 291,
 'closest': 292,
 'sun': 293,
 'father': 294,
 'computers': 295,
 'charlesbabbage': 296,
 'mexico': 297,
 'mexicocity': 298,
 'colors': 299,
 'rainbow': 300,
 'musical': 301,
 'instrument': 302,
 'black': 303,
 'white': 304,
 'keys': 305,
 'piano': 306,
 'americas': 307,
 '1492': 308,
 'christophercolumbus': 309,
 'disney': 310,
 'character': 311,
 'long': 312,
 'nose': 313,
 'grows': 314,
 'it': 315,
 'when': 316,
 'lying': 317,
 'pinocchio': 318,
 'directed': 319,
 'movie': 320,
 'titanic': 321,
 'jamescameron': 322,
 'superhero': 323,
 'also': 324,
 'dark': 325,
 'knight': 326,
 'batman': 327,
 'brasilia': 328,
 'fruit': 329,
 'king': 330,
 'fruits': 331,
 'mango': 332,
 'eiffel': 333,
 'tower': 334}

In [105]:
# Converting Words Into Numerical Tokens
def textToIndices(text, vocab):
  indexedText = []
  for token in tokenizeText(text):
    if token in vocab:
      indexedText.append(vocab[token])
    else:
      indexedText.append(vocab['<UNK>'])
  return indexedText

In [106]:
textToIndices("What is AI", vocab)

[1, 2, 0]

In [107]:
import torch

In [108]:
from torch.utils.data import Dataset , DataLoader

In [109]:
class CustomDataset(Dataset):
  def __init__(self, df, vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self, idx):
    row = self.df.iloc[idx]
    question = textToIndices(row['question'], self.vocab)
    answer = textToIndices(row['answer'], self.vocab)

    return torch.tensor(question), torch.tensor(answer)

In [110]:
dataset = CustomDataset(df, vocab)

In [111]:
dataset[0]

(tensor([1, 2, 3, 4, 5, 6]), tensor([7]))

In [112]:
dataloader = DataLoader(dataset, batch_size=1, shuffle=True)

In [113]:
for ques, ans in dataloader:
  print(ques ,ans[0])

tensor([[ 10, 101,   3, 102]]) tensor([103, 104, 105])
tensor([[ 10, 150,   3, 151, 182,   5,   3,  75, 183]]) tensor([ 72, 184])
tensor([[  1,   2,   3,   4,   5, 123]]) tensor([124])
tensor([[ 1,  2,  3, 36, 37,  5, 38]]) tensor([39])
tensor([[ 10,  30, 140, 141]]) tensor([142])
tensor([[ 45, 329,   2,  66,  67,   3, 330,   5, 331]]) tensor([332])
tensor([[ 1,  2,  3,  4,  5, 78]]) tensor([79])
tensor([[ 1,  2,  3, 74,  5, 56]]) tensor([271])
tensor([[ 1,  2,  3, 97, 98, 99]]) tensor([100])
tensor([[ 45, 261, 262, 128, 263, 264]]) tensor([265])
tensor([[ 1,  2,  3, 53, 54, 20,  3, 48]]) tensor([55])
tensor([[ 45,  91,  92, 252, 253,  20,  42, 254]]) tensor([255])
tensor([[10,  2,  3, 70,  5, 71]]) tensor([72, 73])
tensor([[ 10,  11, 167, 168, 169]]) tensor([170, 171])
tensor([[  1,   2,   3,   4,   5, 145]]) tensor([146])
tensor([[83, 84, 85, 86, 87, 88, 89]]) tensor([90])
tensor([[  1,   2,   3, 156, 157,  20, 158]]) tensor([159])
tensor([[  1,   2,   3, 245,   5, 246]]) tensor([141])
tensor([[ 1,  2,  3,  4,  5, 56]]) tensor([57])
tensor([[ 83,  84, 139,  86,  20,   3,  22,  23]]) tensor([39])
tensor([[ 45, 147,   2, 237,  12,   3, 238, 239]]) tensor([165])
tensor([[ 45, 227, 128, 228, 229,  20,  14, 230,  46]]) tensor([231])
tensor([[45, 19,  2, 66, 67,  3, 68, 19]]) tensor([69])
tensor([[  1,   2,   3,  40, 143,   5,  27]]) tensor([144])
tensor([[ 45, 135,   2,  66,  67,   3, 136, 137]]) tensor([138])
tensor([[ 10,  11, 200, 168, 201]]) tensor([202])
tensor([[  1,   2,   3,   4,   5, 297]]) tensor([298])
tensor([[  1,   2,   3, 110,   5, 111,  20, 112]]) tensor([113, 114, 115, 116])
tensor([[ 1,  2,  3, 18, 19, 20, 21, 22, 23]]) tensor([24])
tensor([[10, 30,  3, 31, 32]]) tensor([33, 34, 35])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([7])
tensor([[  1,   2,   3, 232,   5, 233, 234, 235]]) tensor([236])
tensor([[ 10, 101,   3, 111, 250]]) tensor([251])
tensor([[ 1,  2,  3, 25, 26,  5, 27, 20, 28]]) tensor([29])
tensor([[ 1,  2,  3, 63, 26,  5, 27, 20, 64]]) tensor([65])
tensor([[  1,   2,   3, 151, 127,  88,   3, 288, 289]]) tensor([131])
tensor([[  1,   2,   3, 156,  91,  20,  89, 116, 203]]) tensor([204])
tensor([[  1,   2,   3, 174, 175, 176,  88,  89]]) tensor([177])
tensor([[ 10, 150,   3, 151, 152,  12, 153,  88,   3, 154]]) tensor([155])
tensor([[ 10,  80,   3, 307,  20, 308]]) tensor([309])
tensor([[ 45,   2,   3, 221,  18, 147, 179, 222, 180]]) tensor([123])
tensor([[  1,   2,   3,  97, 147,  20,   3,  48]]) tensor([196])
tensor([[  1,   2,   3,  40,  41,  42, 172]]) tensor([173])
tensor([[ 45, 127, 128,   3, 129,  99, 130]]) tensor([131])
tensor([[ 45, 274, 275,  14, 276, 277, 168, 278]]) tensor([279])
tensor([[  1,   2,   3, 132, 133,  20,   3,  48]]) tensor([134])
tensor([[ 1,  2,  3, 40, 41, 42, 43]]) tensor([44])
tensor([[45, 46, 47, 48, 49, 50, 51]]) tensor([52])
tensor([[ 10,   2,  66,  67,   3, 294,   5, 295]]) tensor([296])
tensor([[ 83,  84, 299,  86,  20,  14, 300]]) tensor([90])
tensor([[ 45, 108,   2,   3,  18]]) tensor([109, 108])
tensor([[ 10,  80, 218]]) tensor([219, 220])
tensor([[ 45, 310, 311, 128,  14, 312, 313, 168, 314, 315, 316, 317]]) tensor([318])
tensor([[ 45,  19, 128,   3, 197, 198]]) tensor([199])
tensor([[  1,   2,   3,   4,   5, 106]]) tensor([107])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([9])
tensor([[ 83,  84, 272, 161,  14, 273, 163]]) tensor([39])
tensor([[ 45, 323,   2, 324,  66,  67,   3, 325, 326]]) tensor([327])
tensor([[ 45, 147, 128,   3, 258,   5, 259]]) tensor([260])
tensor([[ 45, 210,   2,  14, 211, 212, 213, 214]]) tensor([215])
tensor([[ 45, 185,   2,  66,  42, 186, 187,  12, 188, 189]]) tensor([190])
tensor([[  1,  92, 240, 241, 242, 243]]) tensor([244])
tensor([[45, 91, 92, 93, 94, 42, 95]]) tensor([96])
tensor([[  1,   2,   3,   4,   5, 119]]) tensor([328])
tensor([[ 45, 117,   2, 118,  20, 119]]) tensor([120])
tensor([[ 10, 150,   3, 151, 281,  98, 282,   5,   3, 283]]) tensor([284])
tensor([[ 45, 147,   2, 148,  42, 186, 280]]) tensor([106])
tensor([[ 45,  19,   2,   3, 292,  12,   3, 293]]) tensor([215])
tensor([[ 45, 147,   2,  66,  42,   3, 333, 334]]) tensor([6])
tensor([[10, 80, 81]]) tensor([82])
tensor([[ 1,  2,  3, 74,  5,  3, 75, 76]]) tensor([77])
tensor([[ 45, 147,   2, 148,  42, 149]]) tensor([56])
tensor([[  1,   2,   3,  36,  37,   5, 256]]) tensor([257])
tensor([[ 45, 178,   2,   3,  18, 179, 180]]) tensor([181])
tensor([[ 45,   2,   3, 285, 222, 286]]) tensor([287])
tensor([[ 45, 301, 302, 128, 303, 168, 304, 305]]) tensor([306])
tensor([[ 10,  80, 121]]) tensor([103, 122])
tensor([[10, 58,  3, 59,  5, 60]]) tensor([61, 62])
tensor([[ 45, 266,   2, 267,  88, 268, 269]]) tensor([270])
tensor([[ 10, 319,   3, 320, 321]]) tensor([322])
tensor([[ 83,  84, 160, 161,  14, 162, 163]]) tensor([164])
tensor([[ 83,  84, 205,  86,  20,   3, 206, 207, 208]]) tensor([209])
tensor([[  1,   2,   3,   4,   5, 216]]) tensor([217])
tensor([[  1,   2,   3,   4,   5, 247, 248]]) tensor([249])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([16, 17])
tensor([[  1,   2,   3, 223,   5,  14, 224, 225]]) tensor([226])
tensor([[  1,   2,   3,  53, 191, 192, 193, 194]]) tensor([195])
tensor([[  1,   2,   3,  74,   5, 165]]) tensor([166])
tensor([[  1,   2,   3,   4,   5, 290]]) tensor([291])
tensor([[  1,   2,   3,  18, 125,  88,  89]]) tensor([126])

In [114]:
import torch.nn as nn

In [115]:
class Model(nn.Module):
    def __init__(self, vocabSize):
        super().__init__()
        self.embed = nn.Embedding(vocabSize, 50)
        self.rnn = nn.RNN(50, 64, batch_first=True)
        self.fc = nn.Linear(64, vocabSize)

    def forward(self, question):
      embeddedQues = self.embed(question)
      hidden, final = self.rnn(embeddedQues)
      output = self.fc(final.squeeze(0))
      return output

In [122]:
learningRate = 0.001
epochs = 50

In [117]:
RNNModel = Model(len(vocab))

In [118]:
lossFunc = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(RNNModel.parameters(), lr=learningRate)

In [123]:
for epoch in range(epochs):
  totalLoss = 0
  for question, answer in dataloader:
    optimizer.zero_grad()
    output = RNNModel(question)

    target = answer[0][0]
    loss = lossFunc(output, target.unsqueeze(0))

    loss.backward()

    optimizer.step()

    totalLoss = totalLoss + loss.item()

  print(f"Epoch: {epoch+1}, Loss: {totalLoss/len(dataloader):4f}")

Epoch: 1, Loss: 0.000009
Epoch: 2, Loss: 0.000009
Epoch: 3, Loss: 0.000008
Epoch: 4, Loss: 0.000008
Epoch: 5, Loss: 0.000008
Epoch: 6, Loss: 0.000007
Epoch: 7, Loss: 0.000007
Epoch: 8, Loss: 0.000007
Epoch: 9, Loss: 0.000006
Epoch: 10, Loss: 0.000006
Epoch: 11, Loss: 0.000006
Epoch: 12, Loss: 0.000006
Epoch: 13, Loss: 0.000005
Epoch: 14, Loss: 0.000005
Epoch: 15, Loss: 0.000005
Epoch: 16, Loss: 0.000005
Epoch: 17, Loss: 0.000004
Epoch: 18, Loss: 0.000004
Epoch: 19, Loss: 0.000004
Epoch: 20, Loss: 0.000004
Epoch: 21, Loss: 0.000004
Epoch: 22, Loss: 0.000004
Epoch: 23, Loss: 0.000003
Epoch: 24, Loss: 0.000003
Epoch: 25, Loss: 0.000003
Epoch: 26, Loss: 0.000003
Epoch: 27, Loss: 0.000003
Epoch: 28, Loss: 0.000003
Epoch: 29, Loss: 0.000003
Epoch: 30, Loss: 0.000002
Epoch: 31, Loss: 0.000002
Epoch: 32, Loss: 0.000002
Epoch: 33, Loss: 0.000002
Epoch: 34, Loss: 0.000002
Epoch: 35, Loss: 0.000002
Epoch: 36, Loss: 0.000002
Epoch: 37, Loss: 0.000002
Epoch: 38, Loss: 0.000002
Epoch: 39, Loss: 0.000002
Epoch: 40, Loss: 0.000002
Epoch: 41, Loss: 0.000002
Epoch: 42, Loss: 0.000001
Epoch: 43, Loss: 0.000001
Epoch: 44, Loss: 0.000001
Epoch: 45, Loss: 0.000001
Epoch: 46, Loss: 0.000001
Epoch: 47, Loss: 0.000001
Epoch: 48, Loss: 0.000001
Epoch: 49, Loss: 0.000001
Epoch: 50, Loss: 0.000001

In [124]:
def predict(model, question, threshold=0.5):

  numericalQuestion = textToIndices(question, vocab)
  question_tensor = torch.tensor(numericalQuestion).unsqueeze(0)
  output = RNNModel(question_tensor)

  probs = torch.nn.functional.softmax(output, dim=1)
  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("I don't know")

  print(list(vocab.keys())[index])

In [126]:
predict(RNNModel, "What is the largest planet in our solar system?")

jupiter

In [127]:
predict(RNNModel, "Who wrote 'To Kill a Mockingbird'?")

harper